### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by cliGM** [AwkwardTurtle42/TroikaDiscordBot#4]
Hello, I am looking to use this code in a project but it has no license, I would ask that you include a license to this project so permissions on how it can be used are more clear, I'd be more then willing to provide any code back to this repository, (So far I've only declared intents for use with the current discord API)

**Comment by AwkwardTurtle42** [comment]
Hiya, just added a CC0 license.

Although I'll warn you I have no idea if this code actually works anymore, and I'm also a terrible programmer, so use at your own risk.

**Comment by cliGM** [comment]
It works with some modifications, once I have it stable I'll see if I can push an update back. Thank you very much.
